"""empty message

Revision ID: 0046c98c6833
Revises: b6f56727b12b
Create Date: 2022-12-10 20:28:59.088364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0046c98c6833'
down_revision = 'b6f56727b12b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emaillist', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_emaillist_emailadd'), ['emailadd'])

    with op.batch_alter_table('guide', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_user_email'), ['email'])
        batch_op.create_unique_constraint(batch_op.f('uq_user_name'), ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_name'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_user_email'), type_='unique')

    with op.batch_alter_table('guide', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('title')

    with op.batch_alter_table('emaillist', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_emaillist_emailadd'), type_='unique')

    # ### end Alembic commands ###
