"""empty message

Revision ID: 3b6469909f5c
Revises: fdeae6f8d8be
Create Date: 2022-12-31 20:37:15.558034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b6469909f5c'
down_revision = 'fdeae6f8d8be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('help', schema=None) as batch_op:
        batch_op.drop_column('topic')

    with op.batch_alter_table('newssource', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pattern', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('tag', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('rss', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('newssource', schema=None) as batch_op:
        batch_op.drop_column('rss')
        batch_op.drop_column('tag')
        batch_op.drop_column('pattern')

    with op.batch_alter_table('help', schema=None) as batch_op:
        batch_op.add_column(sa.Column('topic', sa.VARCHAR(length=1000), nullable=True))

    # ### end Alembic commands ###
