"""empty message

Revision ID: fdeae6f8d8be
Revises: 0046c98c6833
Create Date: 2022-12-13 20:57:05.345741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdeae6f8d8be'
down_revision = '0046c98c6833'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guide_like', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guide_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_guide_like_user_id_user'), 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_guide_like_guide_id_guide'), 'guide', ['guide_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guide_like', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_guide_like_guide_id_guide'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_guide_like_user_id_user'), type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('guide_id')

    # ### end Alembic commands ###
